name: Initialize Badges

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  init-badges:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create badges directory
        run: mkdir -p .github/badges

      - name: Initialize Backend Coverage Badge
        uses: emibcn/badge-action@v1
        with:
          label: 'Backend Coverage'
          status: 'N/A'
          color: 'lightgrey'
          path: .github/badges/backend-coverage.svg

      - name: Initialize Frontend Coverage Badge
        uses: emibcn/badge-action@v1
        with:
          label: 'Frontend Coverage'
          status: 'N/A'
          color: 'lightgrey'
          path: .github/badges/frontend-coverage.svg

      - name: Commit Initial Badges
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: initialize coverage badges'
          file_pattern: '.github/badges/*.svg' 